### ISSUE TITLE
Pictures only save temporarily

### ISSUE THREAD

**Issue by Tarinu** [RTougjas/TP2015#23]
This is a limitation of heroku, pictures will save permanently on a proper server.

**Comment by RTougjas** [comment]
Fixed it by saving photos to a remote server via ftp.

**Comment by RTougjas** [comment]
Turns out, not fixed. ftp works from localhost, but heroku does not support ftp. 

Perhaps we should consider connecting over ssh and using scp to send files to steffi.ee

**Comment by Tarinu** [comment]
Fixed in  7572b5f, turns out heroku doesn't support ftp by default and has to be enabled in composer.
