### ISSUE TITLE
SQL Query error when providing two tags with exact same value. 

### ISSUE THREAD

**Issue by RTougjas** [RTougjas/TP2015#31]
ERROR: duplicate key value violates unique constraint "unique_picture_tag" DETAIL: Key (picture_id, tag_id)=(70, 30) already exists.

when uploading photo, if one types two (or possible) more tags with the same value, above error occurs, which should not. 

My guess: Unnecessary constraint.

**Comment by Tarinu** [comment]
In my opinion this works as intended, you shouldn't be able to add the same tag multiple times.
