### ISSUE TITLE
local apache environmental variables

### ISSUE THREAD

**Issue by RTougjas** [RTougjas/TP2015#33]
Lets agree on the same environmental variables, then we don't have to edit database.conf file every time pulling or pushing.

**Comment by Tarinu** [comment]
You can edit apache httpd.conf file and add a line something like 
SetEnv DATABASE_URL postgres://... at the end

**Comment by RTougjas** [comment]
yesh. But we all need the same env variables configured so we don't have to change or comment out them every time.
