### ISSUE TITLE
Creation time on comments is wrong

### ISSUE THREAD

**Issue by Tarinu** [RTougjas/TP2015#71]
Date part seems to be correct but time is wrong. It shows the wrong hour and minutes are always 11

**Comment by RTougjas** [comment]
Probably servertime is wrong. Will fix it.
![screen shot 2015-11-23 at 04 11 12](https://cloud.githubusercontent.com/assets/6679681/11328714/52242cba-9198-11e5-87f9-a64702b1534c.png)

**Comment by RTougjas** [comment]
Changed timezone to Estonia/Tallinn in php.ini file. Now it's correct.
