### ISSUE TITLE
Uploaded pictures are not displaying

### ISSUE THREAD

**Issue by UmarZrp** [RTougjas/TP2015#80]
Probably related to the PHP errors that are given.

1. Log in
2. Open Uploads page
3. Fill in all required fields to upload a picture
4. Open all pictures (The uploaded file is not present)
Alternative:
4. Open user settings panel
5. Open "pildid"
7. Picture is not present

The uploaded picture is nowhere to be found and is not displayed anywhere.

**Comment by RTougjas** [comment]
yes, photos are displayed. Note that there are 9 photos displayed on each page. and on bottom of a page, there is navigational links "eelmised" and "järgmised"
